imports:
  - { resource: _definitions.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\ResourceBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,ResourceBundle.php}'

  PhpGuild\ResourceBundle\Action\:
    resource: ../../Action
    tags: [ controller.service_arguments ]

  PhpGuild\ResourceBundle\Router\Loader:
    tags: [ routing.loader ]

  Symfony\Bundle\SecurityBundle\Security\FirewallMap:
    alias: security.firewall.map
